configAsCode:
  revision: main
  repo: https://github.com/validatedpatterns-demos/ansible-edge-gitops-hmi-config-as-code.git

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

aapManifest:
  key: secret/data/hub/aap-manifest
