{{- range $vm, $vmr := .Values.vms }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: es-cloudinit-{{ $vmr.role }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 90s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: cloudinit-{{ $vmr.role }}
    template:
  dataFrom:
    - extract:
        key: {{ coalesce $vmr.cloudinitsecret $.Values.cloudInitDefaultSecretName }}
{{- $ctr := int (coalesce $vmr.count 1) }}
{{- range $i := until $ctr }}
{{- $idx := printf "%03d" (add $i 1) }}
{{- $identifier := printf "%s-%s-%s" $vmr.os $vmr.role $idx }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: es-authorizedsshkeys-{{ $identifier }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 90s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: authorizedsshkeys-{{ $identifier }}
    template:
  data:
    - secretKey: key
      remoteRef:
        key: {{ $vmr.sshsecret }}
        property: {{ $vmr.sshpubkeyfield }}
---
apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1610612736
          }
        ]
      argocd.argoproj.io/sync-wave: "2"
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    labels:
      app: {{ $identifier }}
      edge-gitops-role: {{ $vmr.role }}
      vm.kubevirt.io/template: {{ $vmr.template }}
      vm.kubevirt.io/template.revision: "1"
      vm.kubevirt.io/template.version: v0.19.4
    name: {{ $identifier }}
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: {{ $identifier }}
      spec:
        sourceRef:
          kind: DataSource
          name: {{ $vmr.os }}
          namespace: openshift-virtualization-os-images
        pvc:
          accessModes:
            - {{ coalesce $vmr.accessMode $.Values.defaultAccessMode "ReadWriteOnce" }}
          resources:
            requests:
              storage: {{ $vmr.storage }}
          storageClassName: {{ coalesce $vmr.storageClassName $.Values.defaultStorageClassName "gp2" }}
          volumeMode: {{ coalesce $vmr.volumeMode $.Values.defaultVolumeMode "Filesystem" }}
    running: true
    template:
      metadata:
        annotations:
          vm.kubevirt.io/flavor: {{ $vmr.flavor }}
          vm.kubevirt.io/os: {{ $vmr.os }}
          vm.kubevirt.io/workload: {{ $vmr.workload }}
        labels:
          kubevirt.io/domain: {{ $identifier }}
          kubevirt.io/size: {{ $vmr.flavor }}
          vm.kubevirt.io/name: {{ $identifier }}
      spec:
        accessCredentials:
          - sshPublicKey:
              propagationMethod:
                configDrive: {}
              source:
                secret:
                  secretName: authorizedsshkeys-{{ $identifier }}
        domain:
          cpu:
            cores: {{ $vmr.cores }}
            sockets: {{ $vmr.sockets }}
            threads: {{ $vmr.threads }}
          devices:
            disks:
            - disk:
                bus: virtio
              name: {{ $identifier }}
            - disk:
                bus: virtio
              name: cloudinitdisk
            inputs:
            - bus: virtio
              name: tablet
              type: tablet
            interfaces:
            - masquerade: {}
              name: default
            networkInterfaceMultiqueue: true
            rng: {}
          machine:
            type: pc-q35-rhel8.4.0
          resources:
            requests:
              memory: {{ $vmr.memory }}
        evictionStrategy: LiveMigrate
        networks:
        - name: default
          pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
        - dataVolume:
            name: {{ $identifier }}
          name: {{ $identifier }}
        - name: cloudinitdisk
          cloudInitConfigDrive:
            secretRef:
              name: cloudinit-{{ $vmr.role }}
- apiVersion: v1
  kind: Service
  metadata:
    name: {{ $identifier }}
    annotations:
      argocd.argoproj.io/sync-wave: "2"
    labels:
      app: {{ $identifier }}
      edge-gitops-role: {{ $vmr.role }}
  spec:
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports: {{ $vmr.ports | toPrettyJson }}
    selector:
      vm.kubevirt.io/name: {{ $identifier }}
    sessionAffinity: None
    type: NodePort
kind: List
metadata: {}
{{- end }}
{{- end }}
