---
- name: Discover Ansible Controller Credentials
  ansible.builtin.import_playbook: ansible_get_credentials.yml

- name: Set parameters needed for configuring controller from values.yaml
  ansible.builtin.import_playbook: get_controller_values_overrides.yml

- name: Extract secrets from Kubernetes
  ansible.builtin.import_playbook: parse_secrets_from_k8s.yml

- name: Configure AAP using credentials
  ansible.builtin.import_playbook: configure_aap.yml
