#!/usr/bin/env ansible-playbook
---
- name: Retrieve Credentials from Kubernetes for use in AAP
  become: false
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
  tasks:
    - name: Retrieve manifest file
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: ansible-automation-platform
        name: aap-manifest
      register: manifest_secret
      until: manifest_secret.resources | length == 1
      retries: 20
      delay: 5

    - name: Set manifest fact
      ansible.builtin.set_fact:
        manifest_file: "{{ manifest_secret.resources[0].data.b64content | b64decode | b64decode }}"

    - name: Write temp manifest file
      ansible.builtin.tempfile:
        state: file
        suffix: .zip
      register: manifest_file_tmp

    - name: Set manifest_file_ref fact
      ansible.builtin.set_fact:
        manifest_file_ref: "{{ manifest_file_tmp.path }}"

    - name: Copy manifest contents to tmpfile
      ansible.builtin.copy:
        content: "{{ manifest_file }}"
        dest: "{{ manifest_file_ref }}"
        mode: "0644"

    - name: Retrieve kubeconfig secret
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: openshift-kube-apiserver
        name: node-kubeconfigs
      register: node_kubeconfigs
      until: node_kubeconfigs.resources | length == 1
      retries: 20
      delay: 5

    - name: Parse out vault configmap data
      kubernetes.core.k8s_info:
        kind: ConfigMap
        namespace: vault
        name: openshift-service-ca.crt
      register: vault_ca_cm

    - name: Retrieve CA field
      ansible.builtin.set_fact:
        vault_ca: "{{ vault_ca_cm.resources[0].data['service-ca.crt'] }}"

    - name: Retrieve config details about vault
      kubernetes.core.k8s_info:
        name: vaultkeys
        namespace: imperative
        kind: Secret
      register: vault_secret

    - name: Parse out vault secret data
      ansible.builtin.set_fact:
        vault_data: "{{ vault_secret.resources[0].data.vault_data_json | b64decode | from_json }}"

    - name: Set secrets for use in load controller playbook
      ansible.builtin.set_fact:
        secrets:
          manifest_file_ref: "{{ manifest_file_ref }}"
          kubeconfig: "{{ node_kubeconfigs.resources[0].data['lb-ext.kubeconfig'] | b64decode }}"
          vault_ca: "{{ vault_ca }}"
          vault_root_token: "{{ vault_data.root_token  }}"
          vault_url: https://vault.vault.svc:8200
